//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public int P_ID { get; set; }
        public Nullable<int> P_BOARDID { get; set; }
        public Nullable<int> P_POSTERID { get; set; }
        public string P_POSTER { get; set; }
        public string P_PICTURE { get; set; }
        public string P_Title { get; set; }
        public string P_CONTENTS { get; set; }
        public string p_EMOJI { get; set; }
        public Nullable<System.DateTime> P_DATETIME { get; set; }
        public Nullable<int> P_CLICK { get; set; }
        public string P_BOARDNAME { get; set; }
    }
}
