//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTCOMMENT
    {
        public int PC_ID { get; set; }
        public Nullable<int> PC_BOARDID { get; set; }
        public Nullable<int> PC_POSTID { get; set; }
        public Nullable<int> PC_COMMENTERID { get; set; }
        public string PC_COMMENTER { get; set; }
        public string PC_PICTURE { get; set; }
        public string PC_CONTENTS { get; set; }
        public string PC_EMOJI { get; set; }
        public Nullable<int> PC_GOOD { get; set; }
        public Nullable<int> PC_BAD { get; set; }
        public Nullable<System.DateTime> PC_DATETIME { get; set; }
    }
}
