//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string Accounts { get; set; }
        public string Password { get; set; }
        public string Nickname { get; set; }
        public string Sex { get; set; }
        public string Hobby { get; set; }
        public string Collect { get; set; }
        public string PhoneNum { get; set; }
        public string E_mail { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Label { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string UserLogo { get; set; }
        public string Motto { get; set; }
        public Nullable<int> Permission { get; set; }
        public string Note { get; set; }
    }
}
