//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wang : DbContext
    {
        public Wang()
            : base("name=Wang")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adminUser> adminUser { get; set; }
        public DbSet<BOARD> BOARD { get; set; }
        public DbSet<NOTICE> NOTICE { get; set; }
        public DbSet<Permission> Permission { get; set; }
        public DbSet<POST> POST { get; set; }
        public DbSet<POSTCOMMENT> POSTCOMMENT { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
